on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            HOSTNAME: ${{secrets.HOST_DNS}}
            USER_NAME: ${{secrets.USERNAME}}
            PROJECT_DIR: ${{secrets.PROJECT_DIRECTORY}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /home/ubuntu/monk-coffee-wifi &&
              git checkout main &&
              git fetch --all &&
              git reset --hard origin/main &&
              git pull origin main'
